CREATE DATABASE DB_DRY_SCHOOL;

USE DB_DRY_SCHOOL;

CREATE TABLE TB_ESTUDANTE(
ID bigint auto_increment,
NOME varchar(1000),
IDADE INT,
TURMA CHAR(255),
SERIE INT,
NOTA FLOAT(1),
primary key (ID)
);

INSERT INTO TB_ESTUDANTE (NOME,IDADE,TURMA,SERIE,NOTA)
VALUES ("RICARDO ABREU", 12,"TARDE",7, 9.8),
("SIMONE SANCHES", 11,"MANHA",6, 8.7),
("MONIQUE FERRACINI", 16,"TARDE",2, 6.5),
("GRACIELLE ARRUDA", 11,"TARDE",5, 8.7),
("MARCOS PAULO", 12,"TARDE",6, 5.1),
("JENNIFER SILVA", 14,"MANHÃ",8, 9.0),
("VIVIANE BITENCOURT", 10,"TARDE",4, 10.0),
("DENIS CARVALHO", 9,"TARDE",3, 6.8);

SELECT * FROM TB_ESTUDANTE;
SELECT * FROM TB_ESTUDANTE where NOTA > 7.0;
SELECT * FROM TB_ESTUDANTE WHERE NOTA < 7.0;

UPDATE TB_ESTUDANTE SET TURMA = "MANHA" WHERE ID = 7;






