CREATE DATABASE DB_RH_HELFSTEIN;

USE DB_RH_HELFSTEIN;

CREATE TABLE TB_FUNCIONARIOS(
ID bigint auto_increment,
NOME varchar(1000),
IDADE INT,
DEPTO CHAR(255),
FUNCAO CHAR(255),
SALARIO FLOAT(2),
primary key (ID)
);

INSERT INTO TB_FUNCIONARIOS (NOME,IDADE,DEPTO,FUNCAO,SALARIO)
VALUES ("MARGARIDA",25,"TECNOLOGIA","DEV PLENA",8500.00),
("RICARDO",30,"TECNOLOGIA","DEV JUNIOR",6000.00),
("SANTORO",52,"LIMPEZA","AJUDANTE",1300.00),
("CINTHIA",42,"LIMPEZA","CORDENADORA",1950.00),
("RICHARD",41,"TECNOLOGIA","DEV PLENO",27562.00);

SELECT * FROM TB_FUNCIONARIOS;
SELECT * FROM TB _FUNCIONARIOS WHERE SALARIO > 2000.00;
SELECT * FROM TB _FUNCIONARIOS WHERE SALARIO <= 2000.00;

UPDATE TB_FUNCIONARIOS SET SALARIO = 2300.00 WHERE ID = 3;

DELETE FROM TB_FUNCIONARIOS WHERE ID = 4;

