CREATE DATABASE DB_ELETRONICOS_PRODUTOS;

USE DB_ELETRONICOS_PRODUTOS;

CREATE TABLE TB_PRODUTOS(
ID BIGINT AUTO_INCREMENT,
NOME varchar(1000),
MARCA CHAR(255),
MODELO CHAR(255),
CATEGORIA CHAR(255),
PRECO FLOAT(2),
PRIMARY KEY (ID)
);

INSERT INTO TB_PRODUTOS (NOME,MARCA,MODELO,CATEGORIA,PRECO)
VALUES ("NOTEBOOK", "ACER","GTHUI8569","TURBO", 3560.87);
INSERT INTO TB_PRODUTOS (NOME,MARCA,MODELO,CATEGORIA,PRECO)
VALUES ("NOTEBOOK", "POSITIVO","KSMIH7852","POWER", 2260.99);
INSERT INTO TB_PRODUTOS (NOME,MARCA,MODELO,CATEGORIA,PRECO)
VALUES ("FONE", "FIFINE","TUP5569","MICRO", 130.80);
INSERT INTO TB_PRODUTOS (NOME,MARCA,MODELO,CATEGORIA,PRECO)
VALUES ("TECLADO", "LOGITECH","TSHU8522","POWER", 108.50);
INSERT INTO TB_PRODUTOS (NOME,MARCA,MODELO,CATEGORIA,PRECO)
VALUES ("MOUSE", "REDDRAGON","13PLUS","GAMER", 60.58);

SELECT * FROM TB_PRODUTOS;
SELECT * FROM TB_PRODUTOS WHERE PRECO > 500;
SELECT * FROM TB_PRODUTOS WHERE PRECO < 500;
UPDATE TB_PRODUTOS SET PRECO = 70.00 WHERE ID = 5;








