CREATE DATABASE DB_PIZZARIA_LEGAL;

USE DB_PIZZARIA_LEGAL;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT (5) AUTO_INCREMENT,
TAMANHO VARCHAR(255) NOT NULL,
PRECO FLOAT (6,2) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE TB_PIZZAS (
ID BIGINT(5) AUTO_INCREMENT,
SABOR VARCHAR (255) NOT NULL,
INGREDIENTES VARCHAR(255),
DESCRICAO VARCHAR(255),
CATEGORIA_ID BIGINT,
PRIMARY KEY (ID),
FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIAS (ID)
);

INSERT INTO TB_CATEGORIAS (TAMANHO, PRECO)
VALUES ("GRANDE", 79.90);
INSERT INTO TB_CATEGORIAS (TAMANHO, PRECO)
VALUES ("MÉDIA", 59.90);
INSERT INTO TB_CATEGORIAS (TAMANHO, PRECO)
VALUES ("PEQUENA", 39.90);
INSERT INTO TB_CATEGORIAS (TAMANHO, PRECO)
VALUES ("BROTINHO", 19.90);
INSERT INTO TB_CATEGORIAS (TAMANHO, PRECO)
VALUES ("GIGANTE", 99.90);

SELECT * FROM TB_CATEGORIAS;

INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES,DESCRICAO, CATEGORIA_ID)
VALUES ("PEPPERONI", "QUEIJO, PEPPERONI E MOLHO DE TOMATE", "A MAIS PICANTE DA CASA", 1);
INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES,DESCRICAO, CATEGORIA_ID)
VALUES ("PEPPERONI", "QUEIJO, PEPPERONI E MOLHO DE TOMATE", "A MAIS PICANTE DA CASA", 2);
INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES,DESCRICAO, CATEGORIA_ID)
VALUES ("PEPPERONI", "QUEIJO, PEPPERONI E MOLHO DE TOMATE", "A MAIS PICANTE DA CASA", 3);
INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES,DESCRICAO, CATEGORIA_ID)
VALUES ("4 QUEIJOS", "MUÇARELA, CATUPIRY, GORGONZOLA E PROVOLONE", "UMA EXPLOSÃO DE QUEIJOS!", 1);
INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES,DESCRICAO, CATEGORIA_ID)
VALUES ("4 QUEIJOS", "MUÇARELA, CATUPIRY, GORGONZOLA E PROVOLONE", "UMA EXPLOSÃO DE QUEIJOS!", 3);
INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES,DESCRICAO, CATEGORIA_ID)
VALUES ("STROGONOFF", "CARNE, CREME DE LEITE, MOLHO DE TOMATE E QUEIJO", "AQUELA QUE TODO MUNDO ODEIA AMAR!", 1);
INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES,DESCRICAO, CATEGORIA_ID)
VALUES ("STROGONOFF", "CARNE, CREME DE LEITE, MOLHO DE TOMATE E QUEIJO", "AQUELA QUE TODO MUNDO ODEIA AMAR!", 2);
INSERT INTO TB_PIZZAS (SABOR, INGREDIENTES,DESCRICAO, CATEGORIA_ID)
VALUES ("STROGONOFF", "CARNE, CREME DE LEITE, MOLHO DE TOMATE E QUEIJO", "AQUELA QUE TODO MUNDO ODEIA AMAR!", 3);

SELECT * FROM TB_PIZZAS;

SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS WHERE PRECO > 45;
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS WHERE PRECO >= 50 AND PRECO <= 100;
SELECT * FROM TB_PIZZAS WHERE SABOR LIKE "%M%";
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.CATEGORIA_ID = TB_CATEGORIAS.ID;
SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_PIZZAS.CATEGORIA_ID = TB_CATEGORIAS.ID
WHERE CATEGORIA_ID = 3;